<?php

namespace App\Http\Controllers\Api\v1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class MyMotorController extends Controller
{
    public function register(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nomor_rangka' => [
                'required',
                'string',
            ],
            'phone_number' => [
                'required',
                'string',
                'regex:/^(\+62|62|0)8[1-9][0-9]{7,10}$/',
            ],
            'ktp' => 'required|file|image|mimes:jpg,jpeg,png|max:2048',
            'kk' => 'required|file|image|mimes:jpg,jpeg,png|max:2048',
        ], [
            'nomor_rangka.required' => 'Nomor rangka wajib diisi.',
            'nomor_rangka.string' => 'Nomor rangka harus berupa teks.',
        
            'phone_number.required' => 'Nomor handphone wajib diisi.',
            'phone_number.string' => 'Nomor handphone harus berupa teks.',
            'phone_number.regex' => 'Format nomor handphone tidak valid.',
        
            'ktp.required' => 'Foto KTP wajib diunggah.',
            'ktp.file' => 'KTP harus berupa file.',
            'ktp.image' => 'File KTP harus berupa gambar.',
            'ktp.mimes' => 'KTP harus berformat JPG, JPEG, atau PNG.',
            'ktp.max' => 'Ukuran file KTP maksimal 2MB.',
        
            'kk.required' => 'Foto KK wajib diunggah.',
            'kk.file' => 'KK harus berupa file.',
            'kk.image' => 'File KK harus berupa gambar.',
            'kk.mimes' => 'KK harus berformat JPG, JPEG, atau PNG.',
            'kk.max' => 'Ukuran file KK maksimal 2MB.',
        ]);

        if ($validator->fails()) {
            $firstError = $validator->errors()->first();

            return response()->json([
                'status' => 'error',
                'code' => 422,
                'message' => $firstError,
                'data' => null,
            ], 422);
        }

        // Here you would typically save the motor registration to the database
        // For demonstration, we will just return a success response

        return response()->json([
            'status' => 'success',
            'code' => 200,
            'message' => 'Motor berhasil didaftarkan',
            'data' => [
                'motor_id' => '12345', // This would be generated by your database
                'nomor_rangka' => (string) $request->nomor_rangka,
                'status_verifikasi' => 'pending',
            ]
        ], 200);
    }
}
