<?php

namespace App\Http\Controllers\Api\v1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;
use App\Models\NomorRangka;
use App\Models\MasterPart;
use Illuminate\Support\Facades\Http;

class MyMotorController extends Controller
{
    public function register(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nomor_rangka' => [
                'required',
                'string',
            ],
            'phone_number' => [
                'required',
                'string',
                'regex:/^(\+62|62|0)8[1-9][0-9]{7,10}$/',
            ],
            'ktp' => 'required|file|image|mimes:jpg,jpeg,png|max:2048',
            'kk' => 'required|file|image|mimes:jpg,jpeg,png|max:2048',
        ], [
            'nomor_rangka.required' => 'Nomor rangka wajib diisi.',
            'nomor_rangka.string' => 'Nomor rangka harus berupa teks.',
        
            'phone_number.required' => 'Nomor handphone wajib diisi.',
            'phone_number.string' => 'Nomor handphone harus berupa teks.',
            'phone_number.regex' => 'Format nomor handphone tidak valid.',
        
            'ktp.required' => 'Foto KTP wajib diunggah.',
            'ktp.file' => 'KTP harus berupa file.',
            'ktp.image' => 'File KTP harus berupa gambar.',
            'ktp.mimes' => 'KTP harus berformat JPG, JPEG, atau PNG.',
            'ktp.max' => 'Ukuran file KTP maksimal 2MB.',
        
            'kk.required' => 'Foto KK wajib diunggah.',
            'kk.file' => 'KK harus berupa file.',
            'kk.image' => 'File KK harus berupa gambar.',
            'kk.mimes' => 'KK harus berformat JPG, JPEG, atau PNG.',
            'kk.max' => 'Ukuran file KK maksimal 2MB.',
        ]);

        $ktpPath = $request->file('ktp')->store('uploads/ktp', 'public');
        $kkPath = $request->file('kk')->store('uploads/kk', 'public');

        if ($validator->fails()) {
            $firstError = $validator->errors()->first();

            return response()->json([
                'status' => 'error',
                'code' => 422,
                'message' => $firstError,
                'data' => null,
            ], 422);
        }

        // Here you would typically save the motor registration to the database
        // For demonstration, we will just return a success response

        return response()->json([
            'status' => 'success',
            'code' => 200,
            'message' => 'Motor berhasil didaftarkan',
            'data' => [
                'motor_id' => '12345', // This would be generated by your database
                'nomor_rangka' => (string) $request->nomor_rangka,
                'status_verifikasi' => 'pending',
            ]
        ], 200);
    }

    public function list(Request $request)
    {
        // $user = Auth::user();

        // if (!$user) {
        //     return response()->json([
        //         'status' => 'error',
        //         'code' => 401,
        //         'message' => 'Unauthorized',
        //         'data' => null,
        //     ], 401);
        // }

        // $getAllNomorRangka = NomorRangka::where('user_id', $user->id)->where('status_verifikasi', 'verified')->get();

        // if ($getAllNomorRangka->isEmpty()) {
        //     return response()->json([
        //         'status' => 'error',
        //         'code' => 404,
        //         'message' => 'Tidak ada motor terdaftar',
        //         'data' => null,
        //     ], 404);
        // }

        // gunakan nomor rangka untuk mendapatkan data motor dan servis dari pooling
        // $nomorRangka = 'MH3SG5620PK787104'; // contoh nomor rangka, ganti dengan yang sesuai

        // $url_services = env('GET_URL_SERIVCES');
        // $apiUrl = $url_services . "?id=" . $nomorRangka;
        // $response = Http::withoutVerifying()->get($apiUrl);
        // $data = $response->json();

        // dd($data);

        $registeredMotors = [
            [
                'motor_id' => '12345',
                'motor_model' => 'NMAX',
                'plat_nomor' => 'BA 12 CD',
                'nomor_rangka' => 'ABC1234567890',
                'warna' => 'Hitam',
                'tahun' => '2020',
                'riwayat_servis' => [
                    [
                        'servis_id' => 'svc001',
                        'tanggal_servis' => '2023-01-15',
                    ],
                    [
                        'servis_id' => 'svc002',
                        'tanggal_servis' => '2023-06-15',
                    ],
                ],
            ],
            [
                'motor_id' => '67890',
                'motor_model' => 'Fazzio',
                'plat_nomor' => 'BA 1234 CD',
                'nomor_rangka' => 'XYZ0987654321',
                'warna' => 'Merah',
                'tahun' => '2021',
                'riwayat_servis' => [
                    [
                        'servis_id' => 'svc101',
                        'tanggal_servis' => '2024-03-20',
                    ],
                    [
                        'servis_id' => 'svc201',
                        'tanggal_servis' => '2024-08-18',
                    ],
                ],
            ],
        ];

        return response()->json([
            'status' => 'success',
            'code' => 200,
            'message' => 'Daftar motor berhasil diambil',
            'data' => $registeredMotors,
        ], 200);
    }

    // public function getRiwayatServis($nomorRangka)
    // {
    //     $url_services = env('GET_URL_SERIVCES');
    //     $apiUrl = $url_services . "?id=" . $nomorRangka;
    //     $response = Http::withoutVerifying()->get($apiUrl);
    //     $data = $response->json();

    //     if (!$data) {
    //         return response()->json([
    //             'status' => 'error',
    //             'code' => 404,
    //             'message' => 'Riwayat servis tidak ditemukan.',
    //             'data' => null,
    //         ], 404);
    //     }

    //     foreach ($data as &$innerArray) {
    //         if (isset($innerArray['part_id'])) {
    //             $partIds = json_decode($innerArray['part_id'], true);

    //             $partNames = [];
    //             foreach ($partIds as $partId) {
    //                 $part = MasterPart::where('part_number', $partId)->first();
    //                 if ($part) {
    //                     $partNames[] = $part->part_name;
    //                 } else {
    //                     $partNames[] = 'UNNAME PART';
    //                 }
    //             }

    //             $innerArray['part_name'] = $partNames;
    //         } else {
    //             $innerArray['part_name'] = [];
    //         }
    //     }

    //     $filtered = collect($data)->firstWhere('id', 'SV250109335');
    //     dd($filtered);

    // }
}
